apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-pvc
  namespace: perf-platform
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}