apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
    datasources.yaml: |-
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server.monitoring:32322
            access: proxy
            isDefault: true
            isDefault: false
          - name: Loki
            type: loki
            url: http://loki-stack.monitoring:3100
            access: proxy
          - name: InfluxDB
            type: influxdb
            url: http://influxdb.monitoring:8086
            access: proxy