apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: replication-controller-manager-binding
  namespace: perf-platform
subjects:
  - kind: ServiceAccount
    name: default
    namespace: perf-platform
roleRef:
  kind: Role
  name: replication-controller-manager
  apiGroup: rbac.authorization.k8s.io