apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-pods
  namespace: perf-platform
rules:
  - apiGroups: ["{{ .Values.apiGroup }}"]
    resources: ["{{ .Values.resources }}"]
    verbs: {{ .Values.verbs | toJson }}