loki:
  enabled: true
  serviceName: loki-stack
  headlessServiceName: loki-stack-headless
  memberlistServiceName: loki-stack-memberlist
  persistence:
    enabled: true
    size: 5Gi

promtail:
  enabled: true

grafana:
  enabled: false

server:
  persistentVolume:
    enabled: true
    mountPath: /data/loki
    size: 10Gi

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

ingester:
  zone: "default-zone"