apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: perf-platform
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{  .Values.image }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        env:
        - name: JVM_ARGS
          value: "-Xms{{ .Values.minMemoryLimit }} -Xmx{{ .Values.maxMemoryLimit }}"
        args: ["sh", "-c", "echo 'Apache JMeter Master has started successfully and running' && jmeter --version && tail -f ./jmeter.log"]