apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  namespace: perf-platform
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: jmeter-master
  template:
    metadata:
      labels:
        app: jmeter-master
    spec:
      containers:
      - name: jmeter-master
        image: jmeter/jmeter-master-5.6.3:1.0
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        env:
        - name: JVM_ARGS
          value: "-Xms{{ .Values.minMemoryLimit }} -Xmx{{ .Values.maxMemoryLimit }}"
        args: ["sh", "-c", "echo 'Apache JMeter Master has started successfully and running' && jmeter --version && tail -f ./jmeter.log"]