apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loki.headlessServiceName }}
  labels:
    app.kubernetes.io/name: {{ .Values.loki.headlessServiceName }}
spec:
  clusterIP: None
  ports:
    - port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    app.kubernetes.io/name: {{ .Values.loki.headlessServiceName }}