apiVersion: v1
kind: Service
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app: loki-stack  # Updated to match the Deployment label
  type: ClusterIP
