apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loki.memberlistServiceName }}
  labels:
    app.kubernetes.io/name: {{ .Values.loki.memberlistServiceName }}
spec:
  clusterIP: None
  ports:
    - port: 7946
      protocol: TCP
      targetPort: 7946
  selector:
    app.kubernetes.io/name: {{ .Values.loki.memberlistServiceName }}