apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
  labels:
    app: prometheus
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.server.service.type | default "NodePort" }}  # Default to ClusterIP if not set
  ports:
    - port: {{ .Values.server.service.servicePort | default 80 }}
      targetPort: 9090
      nodePort: {{ .Values.server.service.nodePort | default 32322 }}
      protocol: TCP
      name: http
  selector:
    app: prometheus
    release: {{ .Release.Name }}
