apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  namespace: perf-platform
spec:
  type: LoadBalancer
  ports:
  - name: jenkins-master
    port: 8080
    targetPort: 8080
  - name: jenkins-slave
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins-master